name: DTW App — Load ECR Credentials

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'DTW/App/**'
  push:
    branches: [master]
    paths:
      - 'DTW/App/**'
  create:  # tag creation

jobs:
  load-credentials:
    uses: EliLillyCo/hangar/.github/workflows/load-credentials.yaml@main
    secrets: inherit
